services:
  backend:
    build: ./backend
    container_name: qr-coupon-backend
    ports:
      - "5000:5000"
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

